version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - xcover-bundle-{{ checksum "Gemfile.lock" }}
            - xcover-bundle-

      - run:
          name: Bundle Install
          command: |
            bundle install --path vendor/bundle

      - save_cache:
          key: xcover-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Unit Tests
          command: |
            bundle exec rspec --format documentation spec/*
